config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  resources :cards

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index

    @cards = [
      {
        title: 'test1',
        body: 'hello1'
      },
      {
        title: 'test2',
        body: 'hello2'
      },
      {
        title: 'test3',
        body: 'hello3'
      }
    ]

    @cards << @cards*5
    @cards.flatten!

    @cards = Kaminari.paginate_array(@cards).page(params[:page]).per(10)

  end

  def show
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
  end




end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/index.html.slim
h3 Карточки

= paginate @cards
.row
  -@cards.each do |card|
    .col-xs-1 style="width:300px"
      .panel.panel-default
        .panel-heading
          = card[:title] 
        .panel-body
          = card[:body] 

app/views/cards/show.html.slim
h3 show

app/views/layouts/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.slim
= link_to 'Карточки', cards_path, class: 'navbar-brand'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'History Cards'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'History Cards'}"
    == stylesheet_link_tag "application", :media => 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
  body
    header
      == render 'layouts/navigation'
    main[role="main"]
      == render 'layouts/messages'
      == yield

app/views/visitors/index.html.erb
<h3>Welcome</h3>